export const INIT_WORKITEM = 'INIT_WORKITEM';
export const ADD_WORKITEM = 'ADD_WORKITEM';
export const UPD_WORKITEM = 'UPD_WORKITEM';
export const DELETE_WORKITEM = 'DELETE_WORKITEM';

export const FILTERTYPE_WORKITEM = 'FILTERTYPE_WORKITEM';
export const FILTERUSER_WORKITEM = 'FILTERUSER_WORKITEM';
export const OPEN_BUTTON = 'OPEN_BUTTON';